version: '3'

silent: true

tasks:

  install-frontend:
    dir: price_estimation/frontend
    cmds:
      - npm ci

  start-frontend:
    deps:
      - task: stop-frontend
    dir: price_estimation/frontend
    cmds:
      - ng serve --open

  start-backend:
    dir: price_estimation/backend
    cmds:
      - python3 app.py

  start-price-estimation:
    cmds:
      - task --parallel start-backend start-frontend

  stop-frontend:
    cmds:
      - cmd: kill -9 "$(lsof -sTCP:LISTEN -ti tcp:4200)"
        ignore_error: true

  train-model:
    dir: model
    cmds:
      - python3 train_model.py